// Generated by scripts/sync-shared.mjs from lib/site — edit the original there, not this copy.
// Kept free of the schema (and so of zod), as the browser needs these.

/** The href that opens the quote form instead of going anywhere. */
export const QUOTE_HREF = "#offert";

/** Links that open the quote form rather than going anywhere. */
export function isQuoteHref(href: string): boolean {
  return href === QUOTE_HREF;
}

/** Addresses outside the site, which open in a new tab. */
export function isExternalHref(href: string): boolean {
  return /^https?:\/\//.test(href);
}

/** Addresses that leave the browser for another app (mail, phone). */
export function isAppHref(href: string): boolean {
  return /^(mailto|tel):/.test(href);
}
